Handle missing request file in timeout_requests
Solve a race condition between the user interface and the
action interface REST interface.  It's possible for a user
to delete a request while a timeout scan is in process.  When
this happened you could get an exception from the server, like so:

Server returned message: <body><h1 align="center">FSERVER Error</h1>
<font color="red">Exception raised by fserver software</font>
<pre>
Traceback (most recent call last):
  File "/usr/lib/cgi-bin/fserver.py", line 1382, in <module>
    main(req)
  File "/usr/lib/cgi-bin/fserver.py", line 1367, in main
    action_function(req)
  File "/usr/lib/cgi-bin/fserver.py", line 626, in do_query_requests
    timeout_requests(req)
  File "/usr/lib/cgi-bin/fserver.py", line 1063, in timeout_requests
    request_fd = open(filepath, "r")
IOError: [Errno 2] No such file or directory:
'/home/ubuntu/work/fserver/fserver-data/data/requests/request-2021-01-14_00:00:02.59-pptlab:rpi.json'
</pre>

Avoid this exception by skipping a request that is not found during
the timeout scan.