Fix query where board name has a dash
A bug in parsing the host and board in the run filenames
caused the following exception (noted at the client side):
Server returned message: <body><h1 align="center">FSERVER Error</h1>
<font color="red">Exception raised by fserver software</font>
<pre>
Traceback (most recent call last):
  File "/usr/lib/cgi-bin/fserver.py", line 1389, in <module>
    main(req)
  File "/usr/lib/cgi-bin/fserver.py", line 1374, in main
    action_function(req)
  File "/usr/lib/cgi-bin/fserver.py", line 740, in do_query_runs
    if not item_match(query_board, host_and_board.split(":")[1]):
IndexError: list index out of range
</pre>
If the board name contained a dash (for say "timslab:rpi3-2"),
the split malfunctioned.

Fix this by splitting the filename by "-on-" instead of "-".

Signed-off-by: Tim Bird <tbird20d@yahoo.com>